// components/AboutMe.vue
<template>
  <section id="aboutme" class="w-3/4">
    <h1 class="mb-4">
      Hi 👋🏻, I'm Santi<span v-if="live">
        and you can watch me live on
        <a href="https://twitch.tv/santima10" target="_blank">Twitch</a>
        now
        <div class="circle red inline-block"/></span
      >.
    </h1>
    <p class="mb-2">
      I'm a software engineer who lives in Gijón, Asturias.
    </p>
    <p class="mb-2">
      Currently I work for a company called
      <a target="_blank" href="https://privacycloud.com">Privacy Cloud</a>,
      co-organize
      <a target="_blank" href="https://www.meetup.com/es-ES/GDG-Asturias"
        >GDG Asturias</a
      >
      and I have fun coding some
      <a href="#sideprojects">side projects</a>.
    </p>
    <p class="mb-2">
      I also play basketball 🏀 with some friends on every time I can.
    </p>
  </section>
</template>

<script>
export default {
  data() {
    return {
      live: false
    };
  },
  async mounted() {
    const { data } = await fetch(
      "https://api.twitch.tv/helix/streams?user_login=santima10",
      {
        headers: { "Client-ID": process.env.NUXT_ENV_TWITCH_CLIENT_ID }
      }
    ).then(res => res.json());

    this.live = data?.length > 0;
  }
};
</script>

<style>
@keyframes up-right {
  0% {
    transform: scale();
    opacity: 0.25;
  }
  50% {
    transform: scale (1, 5);
    opacity: 1;
  }
  100% {
    transform: scale(1);
    opacity: 0.25;
  }
}
.circle {
  border-radius: 50%;
  width: 10px;
  height: 10px;
  opacity: 0.25;
}
.red {
  background-color: red;
  animation: up-right 1s infinite;
}
</style>

// src/components/AboutMe/AboutMe.tsx
import Link from "next/link";
import { ReactElement } from "react";
import Typist from "react-typist";

interface Props {
  live: boolean;
}

export function AboutMe({ live }: Props): ReactElement {
  return (
    <section id="aboutme" className="mt-10">
      <h1 className="mb-4">
        <Typist className="social">
          Hi 👋🏻, I&apos;m Santi
          {live && (
            <span v-if="live">
              {" "}
              and you can watch me live on{" "}
              <a
                href="https://twitch.tv/santima10"
                target="_blank"
                rel="noreferrer"
              >
                Twitch{" "}
              </a>
              now <div className="circle red inline-block" />
            </span>
          )}
          .
        </Typist>
      </h1>
      <p className="mb-2">
        I&apos;m a software engineer who lives in Gijón, Asturias.
      </p>
      <p>
        Want to know what am I doing now? Visit{" "}
        <Link href="/now">
          <a>/now</a>
        </Link>
        .
      </p>
    </section>
  );
}
